# Use root/example as user/password credentials
version: '3.7'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: NBS-MYSQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: noble
      
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    container_name: NBS-ADMINER
    ports:
      - 5000:8080


  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    privileged: true
    user: root
    ports:
      - 8083:8080
      - 50003:50000
    container_name: NBS-JENKINS
    volumes:
      - ~/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
