# Use root/example as user/password credentials
version: '3.7'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    container_name: NBS-MYSQL
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: noble
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: "no"
    container_name: NBS-ADMINER
    ports:
      - 5000:8080


  jenkins:
    image: jenkins/jenkins:lts
    restart: "no"
    privileged: true
    user: root
    ports:
      - 8083:8080
      - 50003:50000
    container_name: NBS-JENKINS
    volumes:
      - ~/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock


  backend:
    image: morogoyo/noblecrm-backend:0.1
    restart: "no"
    privileged: true
    depends_on:
      - db
    user: root
    ports:
      - 8080:8080
    container_name: NBS-BACK-END




volumes:
  mysql-data:
